// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

/**
 * @title ZeroCarbonCommute
 * @notice Verified Green Commute Rewards Protocol for BOT Chain
 */
contract ZeroCarbonCommute is ERC20, Ownable, ReentrancyGuard {
    using ECDSA for bytes32;
    using MessageHashUtils for bytes32;

    // --- Protocol Parameters ---
    address public verifierAddress; // Off-chain Oracle/Verifier public key
    uint256 public constant MAX_SPEED_KMH = 25; // Max eco-transit speed threshold (25 km/h)
    uint256 public constant REWARD_PER_KM = 10 * 10**18; // 10 GREEN tokens per km
    uint256 public constant MAX_TRIP_DISTANCE_KM = 100; // Single trip cap (100 km)
    uint256 public constant MAX_TOTAL_SUPPLY = 10_000_000 * 10**18; // 10 Million $GREEN supply cap
    
    uint256 public cooldownPeriod = 1 hours; // Anti-spam delay between submissions

    // --- State Variables ---
    mapping(bytes32 => bool) public processedTrips; // Prevents duplicate/replay attacks
    mapping(address => uint256) public lastTripTimestamp; // Cooldown tracking
    mapping(address => uint256) public totalDistanceMeters; // Lifetime verified user distance

    // --- Events ---
    event TripVerified(
        address indexed user,
        bytes32 indexed tripId,
        uint256 distanceMeters,
        uint256 durationSeconds,
        uint256 rewardAmount
    );
    event VerifierUpdated(address indexed oldVerifier, address indexed newVerifier);
    event CooldownUpdated(uint256 oldCooldown, uint256 newCooldown);

    constructor(address _verifierAddress) 
        ERC20("Zero Carbon Token", "GREEN") 
        Ownable(msg.sender) 
    {
        require(_verifierAddress != address(0), "Invalid verifier address");
        verifierAddress = _verifierAddress;
    }

    /**
     * @notice Submit an off-chain verified trip using a cryptographically signed attestation.
     * @param tripId Unique hash generated by the off-chain oracle for this specific ride.
     * @param distanceMeters Distance travelled in meters.
     * @param durationSeconds Trip duration in seconds.
     * @param routeHash IPFS hash or keccak256 hash of encrypted GPS route telemetry.
     * @param signature Cryptographic signature provided by the verifier node.
     */
    function submitVerifiedTrip(
        bytes32 tripId,
        uint256 distanceMeters,
        uint256 durationSeconds,
        bytes32 routeHash,
        bytes memory signature
    ) external nonReentrant {
        // 1. Anti-Replay Check
        require(!processedTrips[tripId], "Trip already processed");

        // 2. Cooldown & Anti-Spam Check
        require(
            block.timestamp >= lastTripTimestamp[msg.sender] + cooldownPeriod,
            "Cooldown period active"
        );

        // 3. Inputs Validation
        require(distanceMeters > 0 && durationSeconds > 0, "Invalid metrics");
        
        uint256 distanceKm = distanceMeters / 1000;
        require(distanceKm <= MAX_TRIP_DISTANCE_KM, "Trip distance exceeds maximum limit");

        // 4. On-Chain Speed Verification (Meters per Second to KM/H)
        // avgSpeedKmh = (distanceMeters / 1000) / (durationSeconds / 3600)
        uint256 avgSpeedKmh = (distanceMeters * 3600) / (durationSeconds * 1000);
        require(avgSpeedKmh <= MAX_SPEED_KMH, "Speed exceeds zero-carbon threshold");

        // 5. ECDSA Signature Verification
        // Includes address(this) to prevent cross-deployment replay attacks
        bytes32 messageHash = keccak256(
            abi.encodePacked(
                msg.sender,
                address(this),
                tripId,
                distanceMeters,
                durationSeconds,
                routeHash,
                block.chainid
            )
        );
        bytes32 ethSignedMessageHash = messageHash.toEthSignedMessageHash();
        
        require(
            ethSignedMessageHash.recover(signature) == verifierAddress,
            "Invalid or forged trip signature"
        );

        // 6. Reward Calculation & Supply Cap Check
        uint256 rewardAmount = (distanceMeters * REWARD_PER_KM) / 1000;
        require(totalSupply() + rewardAmount <= MAX_TOTAL_SUPPLY, "Max token supply exceeded");

        // 7. State Updates & Minting Real ERC-20 Tokens
        processedTrips[tripId] = true;
        lastTripTimestamp[msg.sender] = block.timestamp;
        totalDistanceMeters[msg.sender] += distanceMeters;

        _mint(msg.sender, rewardAmount);

        emit TripVerified(msg.sender, tripId, distanceMeters, durationSeconds, rewardAmount);
    }

    // --- Admin Operations ---

    function setVerifierAddress(address _newVerifier) external onlyOwner {
        require(_newVerifier != address(0), "Invalid address");
        emit VerifierUpdated(verifierAddress, _newVerifier);
        verifierAddress = _newVerifier;
    }

    function setCooldownPeriod(uint256 _newCooldown) external onlyOwner {
        emit CooldownUpdated(cooldownPeriod, _newCooldown);
        cooldownPeriod = _newCooldown;
    }
}